
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/picturecool?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
logging:
  level:
    root: warn
    org.ywb.demo.dao: trace
  pattern:
    console: '%p%m%n'
server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8
